# Generated by Django 5.2.3 on 2025-06-17 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('authors', models.CharField(max_length=200, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
            },
        ),
    ]
